### ISSUE TITLE
memcache settings not loaded from /etc/graphite-api.yaml

### ISSUE THREAD

**Issue by r3cgm** [pkittenis/graphite-influxdb#18]
Sorry for not posting this as a proper PR but I don't have the time to do it right now.

If you put this in the config:

memcache:
   host: localhost
   # TTL for /metrics/find endpoint only.
   # TTL for /render endpoint is dynamic and based on data interval.
   # Eg for a 24hr query which would dynamically get a 1min interval, the TTL
   # is 1min.
   # (optional)
   ttl: 900
   # (optional) Memcache (compressed) max value length in MB.
   max_value: 16

And then directly modify finder.py to add a new debug:

        logger.debug("memcache_host %s memcache_ttl %s memcache_max_value %s", self.memcache_host, self.memcache_ttl, self.memcache_max_value)
        if self.memcache_host:
            self.memcache = memcache.Client(
                [self.memcache_host], pickleProtocol=-1,
                server_max_value_length=1024**2*self.memcache_max_value)
        else:
            self.memcache = None

You'll get output like this:

Jul  1 15:24:26 server101: [DEBUG] 2016-07-01 15:24:26,856 - finder.__init__() -  memcache_host None memcache_ttl 1800 memcache_max_value 15

The config file parser looked like it was trying to find keys named memcache_host and memcache_ttl but I experimented by using those and it wouldn't work either.

So for now I'm settling with hardcoding the values directly into the code:

        self._setup_logger(config['log_level'], config['log_file'])
        self.memcache_host = 'localhost'
        self.memcache_ttl = 924
        self.memcache_max_value = 17

Note that the logger initialization self._setup_logger() used to appear further down in the code but I had to move it up so I could get the DEBUG out.

For what it's worth, an initial query against 112,000 series now takes approximately 2 seconds to retrieve with the memcache subsystem, vs. 4 seconds without caching.  Definitely worth the trouble!

**Comment by pkittenis** [comment]
Config should be in valid yaml, eg per the readme:

```yaml
    memcache:
       host: localhost
       # TTL for /metrics/find endpoint only.
       # TTL for /render endpoint is dynamic and based on data interval.
       # Eg for a 24hr query which would dynamically get a 1min interval, the TTL
       # is 1min.
       ttl: 900 # (optional)
       max_value: 15 # (optional) Memcache (compressed) max value length in MB.
```

With ttl set to 1 in graphite-api.yaml:

```
> /home/panos/graphite-influxdb/graphite_influxdb/classes/finder.py(87)__init__()
     86         import ipdb; ipdb.set_trace()
ipdb> print self.memcache_ttl
1
```
This works fine per above and there are [tests for it|https://github.com/pkittenis/graphite-influxdb/blob/master/tests/test_influxdb_integration.py#L391].

If you think there is a bug please provide steps to replicate.
