### ISSUE TITLE
Configuration issues/questions

### ISSUE THREAD

**Issue by szop85** [pkittenis/graphite-influxdb#7]
Hey guys,

I'm trying to configure graphite-api with the InfluxDB finder. The initial configuration looks like this:

```
search_index: /srv/graphite/index
finders:
  - graphite_api.finders.whisper.WhisperFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
whisper:
  directories:
    - /srv/graphite/whisper
time_zone: UTC
```

but after changing to the minimal configuration:

```
finders:
  - graphite_api.finders.whisper.WhisperFinder
  - graphite_influxdb.InfluxdbFinder
influxdb:
     db: collectd
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
time_zone: UTC
```

or
```
finders:
  - graphite_api.finders.whisper.WhisperFinder
  - graphite_influxdb.InfluxdbFinder
influxdb:
  db: collectd
  host: 10.0.80.12
  port: 8086
  user: admin
  pass: admin
  log_file: /var/log/graphite_influxdb_finder/graphite_influxdb_finder.log
  log_level: info
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
time_zone: UTC
```

graphite-api is not starting anymore. Unfortunately no log is created :/. I've build a package for graphite-api with fpm like described at [https://github.com/brutasse/graphite-api/tree/master/fpm] and installed it vial dpkg on my Ubuntu 14.04LTS VM. Would be great if can help me out.

Cheers,
Szop

**Comment by szop85** [comment]
Additional info.

We've changed the init script to see the start process in the foreground:

```
2015-09-10 09:32:30 [2752] [INFO] Starting gunicorn 18.0
2015-09-10 09:32:30 [2752] [INFO] Listening at: http://0.0.0.0:8888 (2752)
2015-09-10 09:32:30 [2752] [INFO] Using worker: sync
2015-09-10 09:32:30 [2757] [INFO] Booting worker with pid: 2757
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
2015-09-10 09:32:30 [2752] [INFO] Shutting down: Master
2015-09-10 09:32:30 [2752] [INFO] Reason: Worker failed to boot.
```

Cheers,
Szop

**Comment by szop85** [comment]
Maybe to be a little bit more specific here the steps I used on my fresh installed Ubuntu 14.04LTS minimal VM:

Install pip and upgrade:
```
apt-get update && apt-get upgrade -y
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip list --outdated | cut -d ' ' -f1 | xargs -n1 pip install -U
```

Install needed packages and make graphite-api deb package:
```
apt-get intall git -y
git clone https://github.com/brutasse/graphite-api.git
cd graphite-api/fpm
pip install virtualenv && apt-get install ruby-dev gcc make libffi-dev libssl-dev python-dev -y && gem install fpm
./build-deb.sh
apt-get install -f && dpkg -i graphite-api_1.0.1-1441878771_amd64.deb
pip install https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
```

After that I've edited the .yaml file and tried /etc/init.d/graphite-api restart

Cheers,
Szop

**Comment by szop85** [comment]
Ok,

I've managed to install the Graphite-API with Apache2 and then using the plugins:

Install pip and upgrade:
```
apt-get update && apt-get upgrade -y
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py && ln -s /usr/local/bin/pip /usr/bin/
pip install virtualenv && apt-get install git ruby-dev gcc make libffi-dev libssl-dev python-dev -y
pip list --outdated | cut -d ' ' -f1 | xargs -n1 pip install -U
pip install https://github.com/thomsonreuters/graphite-api/archive/1.0.2-rc1.tar.gz
pip install https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz

apt-get install apache2 libapache2-mod-wsgi -y
mkdir -p /srv/graphite/ && chown -R www-data: /srv/graphite/

mkdir -p /var/www/wsgi-scripts/
vim /var/www/wsgi-scripts/graphite-api.wsgi :
from graphite_api.app import app as application
```
vim /etc/apache2/sites-available/graphite.conf:
```
LoadModule wsgi_module modules/mod_wsgi.so

WSGISocketPrefix /var/run/wsgi

Listen 8013
<VirtualHost *:8013>

    WSGIDaemonProcess graphite-api processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120
    WSGIProcessGroup graphite-api
    WSGIApplicationGroup %{GLOBAL}
    WSGIImportScript /var/www/wsgi-scripts/graphite-api.wsgi process-group=graphite-api application-group=%{GLOBAL}

    WSGIScriptAlias / /var/www/wsgi-scripts/graphite-api.wsgi

    <Directory /var/www/wsgi-scripts/>
        Order deny,allow
        Allow from all
    </Directory>
</VirtualHost>
```
vim /etc/graphite-api.yaml:
```
search_index: /srv/graphite/index
finders:
  - graphite_influxdb.InfluxdbFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
influxdb:
   host: localhost
   port: 8086
   user: password
   pass: password
   db:   collectd
```
ln -s /etc/apache2/sites-available/graphite.conf /etc/apache2/sites-enabled/graphite.conf && /etc/init.d/apache2 restart

```
test via curl:
```
http://"IP-Webserver":8013/metrics/find?query=*
```

Cheers,
Szop
